- repo: local
  hooks:
    - id: mdformat
      name: Format Markdown
      entry: mdformat 
      language: python
      types: [markdown]
      args: [--wrap, '80', --number]
      additional_dependencies:
        - mdformat-toc
        - mdformat-gfm
