general.import = ["/home/vic/.config/alacritty/themes/monokai_charcoal_custom.toml"]

[colors.cursor]
cursor = "0xFFFFFF"
text = "0x000000"

[font]
size = 15

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[9;5u"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;6u"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u25C6"
key = "I"
mods = "Control"

[[keyboard.bindings]]
chars = "\u25B6"
key = "M"
mods = "Control"

[window]
opacity = 1

[window.dimensions]
columns = 110
lines = 40
