general.import = ["/home/vic/.config/alacritty/themes/monokai_charcoal_custom.toml"]

[keyboard]
bindings = [
{ key = "[", mods = "Control", action = "ToggleViMode" },
{ chars = "\u2717", key = "Return", mods = "Control" },
{ chars = "\u2713", key = "Return", mods = "Control|Shift" },
{ chars = "\u25C6", key = "I", mods = "Control" },
{ chars = "\u25B6", key = "M", mods = "Control" },
{ chars = "\u2605", key = ",", mods = "Control" },
{ key = "Backspace", mods = "Control", action = "None" }
]

[colors.cursor]
cursor = "0xFFFFFF"
text = "0x000000"

[font]
size = 15

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[window]
opacity = 1

[window.dimensions]
columns = 110
lines = 40
