-- Mapping the leader must happen before plugins are required (otherwise wrong leader will be used)
vim.g.mapleader = ' '
-- vim.g.maplocalleader = ' '

require 'lazy-bootstrap'
require 'lazy-plugins'
require 'options'
require 'remaps'
require 'telescope-setup'
require 'treesitter-setup'
require 'lsp-setup'
require 'cmp-setup'
require 'color-setup'
require 'fugitive-setup'
require 'harpoon-setup'
require 'undotree-setup'
require 'nvim-r-setup'
